[2023-09-23 16:36:04,430: INFO: stage_01_get_data]: 
********************
[2023-09-23 16:36:04,431: INFO: stage_01_get_data]: >>>>> stage one started <<<<<
[2023-09-23 16:36:04,433: INFO: common]: content from configs/config.yaml read successfully!!
[2023-09-23 16:36:04,454: INFO: common]: Directory is created at data/cat
[2023-09-23 16:36:04,454: ERROR: stage_01_get_data]: [Errno 2] No such file or directory: '../outside_data/cat'
Traceback (most recent call last):
  File "/Users/mfho-27019739/Desktop/AIML/Github/AIOPS-DL-Pipeline-CNN-TF/src/stage_01_get_data.py", line 45, in <module>
    get_data(config_path=parsed_args.config)
  File "/Users/mfho-27019739/Desktop/AIML/Github/AIOPS-DL-Pipeline-CNN-TF/src/stage_01_get_data.py", line 34, in get_data
    copy_files(source_data_dir, local_data_dir)
  File "/Users/mfho-27019739/Desktop/AIML/Github/AIOPS-DL-Pipeline-CNN-TF/src/utils/common.py", line 42, in copy_files
    list_of_files = os.listdir(source_data_dir)
FileNotFoundError: [Errno 2] No such file or directory: '../outside_data/cat'
